python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTh1 --seq_len 96 --pred_len 96 --batch_size 256  --patch_len 16
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTh1 --seq_len 96 --pred_len 192 --batch_size 256 --patch_len 16
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTh1 --seq_len 96 --pred_len 336 --batch_size 256 --patch_len 16
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTh1 --seq_len 96 --pred_len 720 --batch_size 256 --patch_len 16
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTh2 --seq_len 96 --pred_len 96 --batch_size 256 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTh2 --seq_len 96 --pred_len 192 --batch_size 256 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTh2 --seq_len 96 --pred_len 336 --batch_size 256 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTh2 --seq_len 96 --pred_len 720 --batch_size 256 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTm1 --seq_len 96 --pred_len 96 --batch_size 256 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTm1 --seq_len 96 --pred_len 192 --batch_size 256 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTm1 --seq_len 96 --pred_len 336 --batch_size 256 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTm1 --seq_len 96 --pred_len 720 --batch_size 256 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTm2 --seq_len 96 --pred_len 96 --batch_size 256 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTm2 --seq_len 96 --pred_len 192 --batch_size 256 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTm2 --seq_len 96 --pred_len 336 --batch_size 256 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ETTm2 --seq_len 96 --pred_len 720 --batch_size 256 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data Weather --seq_len 96 --pred_len 96 --batch_size 4 --patch_len 16
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data Weather --seq_len 96 --pred_len 192 --batch_size 4 --patch_len 16
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data Weather --seq_len 96 --pred_len 336 --batch_size 4 --patch_len 16
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data Weather --seq_len 96 --pred_len 720 --batch_size 4 --patch_len 16
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ILI --seq_len 96 --pred_len 24 --batch_size 32 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ILI --seq_len 96 --pred_len 36 --batch_size 32 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ILI --seq_len 96 --pred_len 48 --batch_size 32 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data ILI --seq_len 96 --pred_len 60 --batch_size 32 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data Electricity --seq_len 96 --pred_len 96 --batch_size 4 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data Electricity --seq_len 96 --pred_len 192 --batch_size 4 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data Electricity --seq_len 96 --pred_len 336 --batch_size 4 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data Electricity --seq_len 96 --pred_len 720 --batch_size 4 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data Traffic --seq_len 96 --pred_len 96 --batch_size 4 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data Traffic --seq_len 96 --pred_len 192 --batch_size 4 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data Traffic --seq_len 96 --pred_len 336 --batch_size 4 --patch_len 32
python -u run_LTF.py --model LGRU --task_name long_term_forecast --data Traffic --seq_len 96 --pred_len 720 --batch_size 4 --patch_len 32
cmd /k